### ISSUE TITLE
seems like this doesn't read my pyproject.toml

### ISSUE THREAD

**Issue by amirreza8002** [ChartBoost/ruff-action#22]
hi
so i have a pyproject.toml that configures ruff to ignore certain things
this works fine in local
but github action is failing 

`"__init__.py" = ["E402", "F401", "F403"]`
this is one example of my config

pyproject.toml is on the root dir of the project and is pushed to github

**Comment by brucearctor** [comment]
@amirreza8002 -- it would be expected that this works the same, assuming same version of ruff [ which you can pin ].  

Can you create a shareable, reproducible, viewable example?  

Ex:  
* Example Python file that has 'problems' that you want to ignore [ doesn't have to be your file ].  
* your GH workflow file that calls this action
* your pyproject.toml
* Ideally in an Open Source GH repo, so that you can run the workflow and could expect that failure.

**Comment by amirreza8002** [comment]
hi again
sorry, seems like i had some sort of caching problem or similar
not sure why ruff did work without error, but seems like it had an error to begin with
so your all good
thanks for the great tool btw
